import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/ui/themeProvider"
import Header from "@/components/Header/Header"
import { validateSession } from "@/actions/auth"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "AniTeka v2",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await validateSession()

  return (
    <html lang="en">
      <body
        className={`${inter.className} mx-auto bg-[--main-bg] text-[--text-secondary] font-medium antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="logo_mark"></div>
          <Header session={session as any} />
          <div className="mx-auto mt-5 max-w-[1100px] overflow-hidden">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
